## Shell
brew "jq"
brew "fzf"
brew "bash"
brew "gpg"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Software
## Development
cask "iterm2"
cask "sublime-text"
cask "intellij-idea-ce"
cask "1password"


## Productivity
cask "rectangle"

## Other
cask "spotify"