## Shell
brew "jq"
brew "fzf"
brew "bash"
brew "gpg"
cask "gpg-suite"
brew "pinentry-mac"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Software
## Development
brew "docker-compose"
cask "docker"
cask "iterm2"
cask "sublime-text"
cask "1password"
cask "jetbrains-toolbox"


## Productivity
#cask "rectangle"
cask "raycast"
cask "shottr"
cask "notion"

## Other