## Shell
brew "jq"
brew "fzf"
brew "bash"
brew "gpg"
cask "gpg-suite"
brew "pinentry-mac"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Software
## Development
brew "docker-compose"
cask "docker"
cask "iterm2"
cask "sublime-text"
cask "intellij-idea-ce"
cask "1password"


## Productivity
cask "rectangle"

## Other